[package]
name = "mini_axum_event_planner"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
argon2 = { version = "0.5.3", features = ["std"] }
askama = "0.16.0"
askama_web = { version = "0.16", features = ["axum-0.8"] }
axum = "0.8.9"
dotenvy = "0.15.7"
serde = { version = "1.0.229", features = ["derive"] }
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite"] }
time = "0.3.55"
tokio = { version = "1.52.1", features = ["full"] }
tower-sessions = "0.14.0"
tower-sessions-sqlx-store = { version = "0.15.0", features = ["sqlite"] }
